# Generated by Django 4.1.1 on 2022-11-06 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Имя')),
                ('date_birthday', models.DateField(default=None, verbose_name='Дата рождения:')),
                ('country', models.CharField(max_length=50, verbose_name='Страна')),
                ('age', models.PositiveSmallIntegerField(verbose_name='Возраст')),
                ('images', models.ImageField(upload_to='book_site/', verbose_name='Постер')),
                ('biography', models.TextField(max_length=500, verbose_name='Биография')),
            ],
            options={
                'verbose_name': 'Автор',
                'verbose_name_plural': 'Авторы',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
                ('images', models.ImageField(upload_to='book_site/', verbose_name='Постер')),
                ('descriptions', models.TextField(verbose_name='Описание')),
                ('year_edition', models.PositiveSmallIntegerField(default=2000, verbose_name='Дата написания:')),
                ('date_published', models.DateField(auto_now_add=True, verbose_name='Дата публикации')),
                ('url', models.SlugField(max_length=150)),
                ('draft', models.BooleanField(default=False, verbose_name='Черновик')),
                ('author', models.ManyToManyField(related_name='book_author', to='book.author', verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Книга',
                'verbose_name_plural': 'Книги',
                'ordering': ['-date_published'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Категория')),
                ('descriptions', models.TextField(max_length=500, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Имя')),
                ('descriptions', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Жанр',
                'verbose_name_plural': 'Жанры',
            },
        ),
        migrations.CreateModel(
            name='PublishedHouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Имя')),
                ('country', models.CharField(max_length=50, verbose_name='Страна')),
            ],
            options={
                'verbose_name': 'Издатель',
                'verbose_name_plural': 'Издатели',
            },
        ),
        migrations.CreateModel(
            name='Stars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('values', models.PositiveSmallIntegerField(default=0, verbose_name='Значение')),
            ],
            options={
                'verbose_name': 'Звезда рейинга',
                'verbose_name_plural': 'Звезды рейтинга',
            },
        ),
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_interpreter', models.CharField(max_length=150, verbose_name='Автор перевода')),
                ('translate_date', models.DateField(default=None, verbose_name='Дата перевода')),
                ('translate_stage', models.CharField(max_length=50, verbose_name='Стадия перевода')),
            ],
            options={
                'verbose_name': 'Автор перевода',
                'verbose_name_plural': 'Авторы перевода',
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=15, verbose_name='IP-адрес')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.book', verbose_name='Книга')),
                ('stars', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.stars', verbose_name='Звезда')),
            ],
            options={
                'verbose_name': 'Рейтинг',
                'verbose_name_plural': 'Рейтинги',
            },
        ),
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='book.category', verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.ManyToManyField(to='book.genre', verbose_name='Жанр'),
        ),
        migrations.AddField(
            model_name='book',
            name='published_house',
            field=models.ManyToManyField(related_name='book_published_house', to='book.publishedhouse', verbose_name='Издатель'),
        ),
        migrations.AddField(
            model_name='book',
            name='translation',
            field=models.ManyToManyField(related_name='book_translation', to='book.translation', verbose_name='Перевод'),
        ),
    ]
