# Generated by Django 3.2.16 on 2022-12-01 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_alter_suggestbook_url_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suggestbook',
            name='url_book',
        ),
    ]
