# Generated by Django 3.2.16 on 2022-12-01 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_remove_suggestbook_url_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suggestbook',
            name='user_book',
        ),
        migrations.AddField(
            model_name='suggestbook',
            name='url_book',
            field=models.URLField(blank=True, default='', verbose_name='Ссылка на книгу'),
        ),
    ]
