# Generated by Django 3.2.16 on 2022-12-01 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0009_auto_20221201_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suggestbook',
            name='draft',
            field=models.CharField(choices=[('MayBe', 'Рассматривается'), ('Yes', 'Рассмотрена'), ('No', 'Отклонена')], default='MayBe', max_length=5, verbose_name='Стадия рассмотрения'),
        ),
    ]
