# Generated by Django 3.2.16 on 2022-12-01 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0010_alter_suggestbook_draft'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suggestbook',
            name='user_book',
            field=models.FileField(blank=True, upload_to='user_book/12_1', verbose_name='Книга пользователя'),
        ),
    ]
